#!/bin/sh
chown root:wheel /Library/Application\ Support/PackageNotifier/refresh-helper
chmod 6755 /Library/Application\ Support/PackageNotifier/refresh-helper
echo "Thanks for installing PackageNotifier!"